### ISSUE TITLE
Error: install / build fail on FreeBSD // incompatible nan dependenciy

### ISSUE THREAD

**Issue by TomFreudenberg** [indutny/node-netroute#9]
Hi, I am maintaining an unofficial fork for meteor to run it on not yet supported platforms. Currently try to get it run on FreeBSD but on of the last parts is `netroute`.

May you have a look on it?

I guess, that the depended `nan` package is outdated / incompatible.

System FreeBSD FreeBSD-10-2 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666

node: v0.10.40

`npm install netroute`

Error:

```
[root@FreeBSD-10-2 /tmp/node]# bin/npm install netroute
|
> netroute@0.2.5 install /tmp/node/node_modules/netroute
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/netroute/.node-gyp"
gmake: Entering directory '/tmp/node/node_modules/netroute/build'
  CXX(target) Release/obj.target/netroute/src/netroute.o
  CXX(target) Release/obj.target/netroute/src/platform-unix.o
In file included from ../src/platform-unix.cc:3:
In file included from ../node_modules/nan/nan.h:111:
../node_modules/nan/nan_new.h:210:10: error: call to 'New' is ambiguous
  return Nan::imp::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/platform-unix.cc:99:38: note: in instantiation of function template specialization 'NanNew<v8::Int32, unsigned long>' requested here
    info->Set(NanNew<String>("mtu"), NanNew<Int32>(msg->rtm_rmx.rmx_mtu));
                                     ^
../node_modules/nan/nan_new.h:110:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:111:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
1 error generated.
netroute.target.mk:86: recipe for target 'Release/obj.target/netroute/src/platform-unix.o' failed
gmake: *** [Release/obj.target/netroute/src/platform-unix.o] Error 1
gmake: Leaving directory '/tmp/node/node_modules/netroute/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "node" "/tmp/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node/node_modules/netroute
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! netroute@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netroute@0.2.5 install script.
npm ERR! This is most likely a problem with the netroute package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls netroute
npm ERR! There is likely additional logging output above.
npm ERR! System FreeBSD 10.2-RELEASE
npm ERR! command "/tmp/node/bin/node" "/tmp/node/bin/npm" "install" "netroute"
npm ERR! cwd /tmp/node
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by TomFreudenberg** [comment]
I tried to get you package from github and change `nan` to current release 2.1.0

Then the errors are in case of incompatible call from netroute:

```
[root@FreeBSD-10-2 /tmp/node]# bin/npm install ../node-netroute
/
> netroute@0.2.5 install /tmp/node/node_modules/netroute
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/netroute/.node-gyp"
gmake: Entering directory '/tmp/node/node_modules/netroute/build'
  CXX(target) Release/obj.target/netroute/src/netroute.o
../src/netroute.cc:18:3: error: use of undeclared identifier 'NanEscapableScope'
  NanEscapableScope();
  ^
../src/netroute.cc:20:26: error: use of undeclared identifier 'NanNew'
  Local<Object> result = NanNew<Object>();
                         ^
../src/netroute.cc:20:33: error: 'Object' does not refer to a value
  Local<Object> result = NanNew<Object>();
                                ^
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1485:7: note: declared here
class Object : public Value {
      ^
../src/netroute.cc:20:41: error: expected expression
  Local<Object> result = NanNew<Object>();
                                        ^
../src/netroute.cc:21:23: error: use of undeclared identifier 'NanNew'
  Local<Array> ipv4 = NanNew<Array>();
                      ^
../src/netroute.cc:21:30: error: 'Array' does not refer to a value
  Local<Array> ipv4 = NanNew<Array>();
                             ^
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1748:7: note: declared here
class Array : public Object {
      ^
../src/netroute.cc:21:37: error: expected expression
  Local<Array> ipv4 = NanNew<Array>();
                                    ^
../src/netroute.cc:22:23: error: use of undeclared identifier 'NanNew'
  Local<Array> ipv6 = NanNew<Array>();
                      ^
../src/netroute.cc:22:30: error: 'Array' does not refer to a value
  Local<Array> ipv6 = NanNew<Array>();
                             ^
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1748:7: note: declared here
class Array : public Object {
      ^
../src/netroute.cc:22:37: error: expected expression
  Local<Array> ipv6 = NanNew<Array>();
                                    ^
../src/netroute.cc:25:5: error: use of undeclared identifier 'NanReturnUndefined'
    NanReturnUndefined();
    ^
../src/netroute.cc:27:5: error: use of undeclared identifier 'NanReturnUndefined'
    NanReturnUndefined();
    ^
../src/netroute.cc:29:15: error: use of undeclared identifier 'NanNew'
  result->Set(NanNew<String>("IPv4"), ipv4);
              ^
../src/netroute.cc:29:22: error: 'String' does not refer to a value
  result->Set(NanNew<String>("IPv4"), ipv4);
                     ^
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1024:7: note: declared here
class String : public Primitive {
      ^
../src/netroute.cc:30:15: error: use of undeclared identifier 'NanNew'
  result->Set(NanNew<String>("IPv6"), ipv6);
              ^
../src/netroute.cc:30:22: error: 'String' does not refer to a value
  result->Set(NanNew<String>("IPv6"), ipv6);
                     ^
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1024:7: note: declared here
class String : public Primitive {
      ^
../src/netroute.cc:32:3: error: use of undeclared identifier 'NanReturnValue'
  NanReturnValue(result);
  ^
../src/netroute.cc:37:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../src/netroute.cc:39:3: error: no matching function for call to 'SetMethod'
  NODE_SET_METHOD(target, "getInfo", GetInfo);
  ^~~~~~~~~~~~~~~
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/src/node.h:128:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::SetMethod
                        ^~~~~~~~~~~~~~~
/tmp/node/node_modules/netroute/.node-gyp/0.10.40/src/node.h:112:6: note: candidate function [with target_t = v8::Handle<v8::Object>] not viable: no
      overload of 'GetInfo' matching 'v8::InvocationCallback' (aka 'Handle<v8::Value> (*)(const v8::Arguments &)') for 3rd argument
void SetMethod(target_t obj, const char* name,
     ^
19 errors generated.
netroute.target.mk:86: recipe for target 'Release/obj.target/netroute/src/netroute.o' failed
gmake: *** [Release/obj.target/netroute/src/netroute.o] Error 1
gmake: Leaving directory '/tmp/node/node_modules/netroute/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "node" "/tmp/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node/node_modules/netroute
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! netroute@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netroute@0.2.5 install script.
npm ERR! This is most likely a problem with the netroute package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls netroute
npm ERR! There is likely additional logging output above.
npm ERR! System FreeBSD 10.2-RELEASE
npm ERR! command "/tmp/node/bin/node" "/tmp/node/bin/npm" "install" "../node-netroute"
npm ERR! cwd /tmp/node
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by TomFreudenberg** [comment]
Could you be so kind to check that?

Thanks in advance
Tom

**Comment by TomFreudenberg** [comment]
Hey, I changed all occurencies of `<Int32>` to `<Number>` and that gets compiled. As `nan`release was taken automatically release `1.9.0`

**Comment by indutny** [comment]
@TomFreudenberg thanks! perhaps you may be interested in contributing this back? ;)

**Comment by TomFreudenberg** [comment]
:-) sure if Number is correct instead than Int32 I can send you a PR

I am not 100% sure if I miss something but you may review ;-)

**Comment by indutny** [comment]
Of course!

**Comment by TomFreudenberg** [comment]
This are the compiling errors, when using the patch Int32->Numbers and nan 2.1.0

Using node v0.10.40

```
> netroute@0.2.6 install /tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp"
gmake: Entering directory '/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/build'
  CXX(target) Release/obj.target/netroute/src/netroute.o
../src/netroute.cc:18:3: error: use of undeclared identifier 'NanEscapableScope'
  NanEscapableScope();
  ^
../src/netroute.cc:20:26: error: use of undeclared identifier 'NanNew'
  Local<Object> result = NanNew<Object>();
                         ^
../src/netroute.cc:20:33: error: 'Object' does not refer to a value
  Local<Object> result = NanNew<Object>();
                                ^
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1485:7: note: declared
      here
class Object : public Value {
      ^
../src/netroute.cc:20:41: error: expected expression
  Local<Object> result = NanNew<Object>();
                                        ^
../src/netroute.cc:21:23: error: use of undeclared identifier 'NanNew'
  Local<Array> ipv4 = NanNew<Array>();
                      ^
../src/netroute.cc:21:30: error: 'Array' does not refer to a value
  Local<Array> ipv4 = NanNew<Array>();
                             ^
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1748:7: note: declared
      here
class Array : public Object {
      ^
../src/netroute.cc:21:37: error: expected expression
  Local<Array> ipv4 = NanNew<Array>();
                                    ^
../src/netroute.cc:22:23: error: use of undeclared identifier 'NanNew'
  Local<Array> ipv6 = NanNew<Array>();
                      ^
../src/netroute.cc:22:30: error: 'Array' does not refer to a value
  Local<Array> ipv6 = NanNew<Array>();
                             ^
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1748:7: note: declared
      here
class Array : public Object {
      ^
../src/netroute.cc:22:37: error: expected expression
  Local<Array> ipv6 = NanNew<Array>();
                                    ^
../src/netroute.cc:25:5: error: use of undeclared identifier 'NanReturnUndefined'
    NanReturnUndefined();
    ^
../src/netroute.cc:27:5: error: use of undeclared identifier 'NanReturnUndefined'
    NanReturnUndefined();
    ^
../src/netroute.cc:29:15: error: use of undeclared identifier 'NanNew'
  result->Set(NanNew<String>("IPv4"), ipv4);
              ^
../src/netroute.cc:29:22: error: 'String' does not refer to a value
  result->Set(NanNew<String>("IPv4"), ipv4);
                     ^
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1024:7: note: declared
      here
class String : public Primitive {
      ^
../src/netroute.cc:30:15: error: use of undeclared identifier 'NanNew'
  result->Set(NanNew<String>("IPv6"), ipv6);
              ^
../src/netroute.cc:30:22: error: 'String' does not refer to a value
  result->Set(NanNew<String>("IPv6"), ipv6);
                     ^
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/deps/v8/include/v8.h:1024:7: note: declared
      here
class String : public Primitive {
      ^
../src/netroute.cc:32:3: error: use of undeclared identifier 'NanReturnValue'
  NanReturnValue(result);
  ^
../src/netroute.cc:37:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../src/netroute.cc:39:3: error: no matching function for call to 'SetMethod'
  NODE_SET_METHOD(target, "getInfo", GetInfo);
  ^~~~~~~~~~~~~~~
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/src/node.h:128:25: note: expanded from macro
      'NODE_SET_METHOD'
#define NODE_SET_METHOD node::SetMethod
                        ^~~~~~~~~~~~~~~
/tmp/generate-dev-bundle-XXXXXXXX.uryxbV23/build/npm-tool-install/node_modules/netroute/.node-gyp/0.10.40/src/node.h:112:6: note: candidate function
      [with target_t = v8::Handle<v8::Object>] not viable: no overload of 'GetInfo' matching 'v8::InvocationCallback' (aka
      'Handle<v8::Value> (*)(const v8::Arguments &)') for 3rd argument
void SetMethod(target_t obj, const char* name,
     ^
19 errors generated.
```

**Comment by TomFreudenberg** [comment]
Hi Fedor @indutny 

any new decisions or ideas on that ?

Thanks for a short note
Tom

**Comment by santigimeno** [comment]
@TomFreudenberg It looks like you have not adapted the code to the nan2 syntax. You can try this tool to ease the process: https://github.com/nodesource/upgrade-utils

**Comment by TomFreudenberg** [comment]
Ok, thanks, I will have a look

**Comment by TomFreudenberg** [comment]
Hi I send in a new PR for nan 2.1.0 at #11

**Comment by TomFreudenberg** [comment]
Hi I am sorry but last fix missed test on linux platform

I send new PR #12

**Comment by TomFreudenberg** [comment]
Now Travis CI tests are also successful

**Comment by TomFreudenberg** [comment]
After merge of #12 this issue is fixed
